### ISSUE TITLE
Behaviour with multiple AuthenticatingAuthority values

### ISSUE THREAD

**Issue by peter-** [simplesamlphp/simplesamlphp-module-smartattributes#2]
When multiple levels of SAML proxying are involved the current code's [use of only the first value of AuthenticatingAuthority](https://github.com/simplesamlphp/simplesamlphp-module-smartattributes/blob/425836d15914e0e48d5f69b3ec9662093ccb21fc/lib/Auth/Process/SmartID.php#L120-L122) to qualify generated attribute values (when `add_authority=>TRUE`, which is the default) will cause generated attribute values to change *if* a SAML proxy is added earlier in the chain.

Previous situation
------------------------

Institution X (IDP1) access the eduroam CAT service which is located "downstream" of the "eduroam supporting services" SAML Proxy. The eduroam SAML Proxy (as IDP2) asserts the entityID of IDP1 as (only) value of `AuthenticatingAuthority` and the code of this module qualifies attribute values with it, too.

I.e., subjects from Institution X are qualified with the entityID from Institution X's IDP (IDP1) as would be expected.

Current situation
----------------------

Institution X (IDP1) now decides to outsource authentication to an "upstream" IDP0 (M$ Azure AD in this case). As a result IDP1 now itself adds an `AuthenticatingAuthority` (with the entityID of IDP0) to its Assertion. The eduroam SAML Proxy (as IDP2) in turn will add IDP1's entityID as a second `AuthenticatingAuthority` value to its Assertions to "downsteam" SPs such as  the eduroam CAT.  
Likewise, the code of this module (running on IDP2 ) will now qualify asserted attribute values with the value of IDP0 (instead of IDP1), because IDP1 is no longer the **first** value of the AuthenticatingAuthority array.

I.e., subjects from Institution X are now qualified with the entityID from IDP0, which may be unexpected. They may no longer be recognised by SPs "downstream" of the eduroam SAML Proxy that rely on the attribute in question.

How to deal with this
---------------------------

In the above scenario it would be desirable to use the **last**  `AuthenticatingAuthority` value instead of the first one. If that's not sufficiently universal (SAML proxying may be added in different places of the chain, I guess) maybe a configuration option is needed to let the code pick either the first one or the last one. (I can't currently think of any other selection methods than first/last.)

IMHO this hints at conceptual issues with this functionality (or specifically, the reliance on `AuthenticatingAuthority` to qualify attribute values) at least when used with identifiers that already are fully qualified globally unique all by themselfs (e.g. SAML persistent NameIDs, SAML Subject ID Attributes, eduPerson attributes, etc.) which is a common and best practice in some sectors, such as academia / research / higher education.

As **there may not be a way to fix this for existing deployments** (changing the current behaviour to "fix" generated values for some IDPs will create the same kind of breaking change for others) maybe this part from the documentation:

> This can be useful to indicate what SAML IdP was used, in case the original identifier is not scoped. Defaults to `TRUE`.

should be turned into a warning, e.g.:

> Do not use this setting with identifier values that are already sufficiently qualified  e.g. SAML persistent NameIDs, SAML Subject-ID Attributes, eduPerson attributes, etc.).

With or without added text about changes in SAML proxying -- which may be fully outside of the control or even knowledge of the deployer of this code -- possibly changing the generated values.

Though the complexities of NameID processing in general (different Formats, from the Assertion's Subject or from a deprecated `eduPersonTargetedId` Attribute) and specifically within SimpleSAMLphp would likely require more text here, to make sure the proper `NameQualifier` from the NameID itself is used together with the NameID's text content, which would then remove the need for later qualification with the `AuthenticatingAuthority` value. (FTR: Here's my own recipe for [SimpleSAMLphp NameID handling for Service Prioviders](https://gitlab.com/-/snippets/2121223) which no doubt is more involved than it should be.)  
So maybe something specific to (proper) NameID processing within SimpleSAMLphp would be needed here? That's the only common, standardised data format where the qualifier is not readily part of the attribute string value.

**Comment by c00kiemon5ter** [comment]
Hello @peter- and everyone else,

and thanks for this report, it helped me understand the strange behaviour that we see from a connected IdP.

> In the above scenario it would be desirable to use the last AuthenticatingAuthority value instead of the first one. If that's not sufficiently universal (SAML proxying may be added in different places of the chain, I guess) maybe a configuration option is needed to let the code pick either the first one or the last one. (I can't currently think of any other selection methods than first/last.)

Based on what I wrote [here][0] I think this doesn't have to be a configuration option, but the correct behaviour would be to look into the last element. I would urge you to continue the discussion on that other thread, as more people are involved and notified and can chime in.


  [0]: https://github.com/simplesamlphp/simplesamlphp/issues/1431#issuecomment-945643739

**Comment by thijskh** [comment]
Thanks Peter. I've proposed a fix.
